### PR TITLE
optimize: rename ErrMismatch -> MethodMismatch

### PR DESCRIPTION
**Pull request by kortschak**
I feel this is a more evocative name.

As an aside, it is not used anywhere. Is it actually needed?

@btracey @vladimir-ch Please take a look.

### CODE REVIEW

**Comment by btracey** [comment]
LGTM. 

I don't think it's needed, because we switched to panicking on method mismatch.

**Comment by kortschak** [comment]
Then delete?

**Comment by vladimir-ch** [comment]
I am for deleting.

**Comment by btracey** [comment]
SGTM

**Comment by kortschak** [comment]
Deleted.

**Pull request merged**
