### PR TITLE
Add test functions from More, Garbow, Hillstrom (1981)

### PR DESCRIPTION
**Pull request by vladimir-ch**
Implemented all the functions, except for Chebyquad.

### CODE REVIEW

**Comment by btracey** [comment]
LGTM.

**Comment by btracey** [comment]
Is a future PR coming where we actually add them to the testMinimize function?

**Comment by vladimir-ch** [comment]
Yes, that is my plan. We will have to split the test problems into groups according to difficulty, there are (badly scaled) problems that only Newton-based optimizers can handle (at least at the moment). CG will be able to handle most problems, although many only with looser tolerances. Many tests would take eternity with steepest descent.

On a more general note, are there any guidelines for Git usage in gonum? For example, this PR is some 25 commits, but could be squashed into one large commit without much loss of information. What is our standpoint wrt squashing and rebasing? Do we keep merge commits? How strict are we about commit messages (present tense, ...)? @btracey @kortschak

**Comment by kortschak** [comment]
We haven't had any real discussions about commit messages and history maintenance. From a personal position, I dislike long sub-branches and merges, but there is no real basis for that opinion except aesthetics - rebasing has problems because it loses review comments. As far as commit messages go, the kernel commit message guidelines are good for me.

Perhaps this is something that should be discussed.

**Comment by btracey** [comment]
On Jan 4, 2015 8:14 PM, "Vladimír Chalupecký" <notifications@github.com>
wrote:
>
> Yes, that is my plan. We will have to split the test problems into groups
according to difficulty, there are (badly scaled) problems that only
Newton-based optimizers can handle (at least at the moment). CG will be
able to handle most problems, although many only with looser tolerances.
Many tests would take eternity with steepest descent.

Feel free to completely revamp the test structure. The current set was to
make sure things worked,  but now that we have a robust set of functions,
we can have a robust set of tests . I'm not sure the right way to separate
them, but testQuasiNewton and testGradientDecent etc seem life a reasonable
idea

>
> On a more general note, are there any guidelines for Git usage in gonum?
For example, this PR is some 25 commits, but could be squashed into one
large commit without much loss of information. What is our standpoint wrt
squashing and rebasing? Do we keep merge commits? How strict are we about
commit messages (present tense, ...)? @btracey @kortschak

**Comment by vladimir-ch** [comment]
Aesthetics and information. A merge commit for one-commit branch does not contribute much information. Kernel commit message guidelines is what I try to follow in my commits, so using that guideline is fine by me (a short one-line summary in present tense/imperative possibly followed by an empty line and explaining paragraph(s)).

I am no git expert, what do you mean by "rebasing loses review comments", @kortschak ? If I rebase a branch on top of master to bring it up to date, does that lose review comments?

**Comment by kortschak** [comment]
>A merge commit for one-commit branch does not contribute much information.

Agreed.

>If I rebase a branch on top of master to bring it up to date, does that lose review comments?

(Do you mean rebasing master onto the branch or the other way. We should not be rebasing onto master.)

That seems to be the case. I think github links the comments to commit hashes, so when a rebase happens those now dangling commits take the comments with them. I haven't read into this, but my recollection is that this has happened on a project I was working on in the past.

**Comment by vladimir-ch** [comment]
> Do you mean rebasing master onto the branch or the other way. We should not be rebasing onto master.

I mean
```
git rebase master pr-branch
```

I would like to confirm this because online I can find only suggestions to rebase, but no (or old) complaints about lost review comments. Also, github seems to add comments to lines and diffs, not to particular commits.

**Comment by kortschak** [comment]
Yes, OK, master onto pr-branch. 

http://weblog.masukomi.org/2013/02/07/rebasing-a-pull-request-on-github

**Comment by kortschak** [comment]
This is why golang uses gerrit.

**Comment by vladimir-ch** [comment]
> http://weblog.masukomi.org/2013/02/07/rebasing-a-pull-request-on-github

I took the liberty of rebasing this branch on top of master. In my (and git-scm.com book's) terminology this means
```
git checkout add-test-functions
git rebase master
```
The line comments are preserved, only the chronological order has changed, now the commits appear after the comments. The information in the above link therefore seems a bit outdated.

**Pull request merged**
