### PR TITLE
Drop mat64.Register call

### PR DESCRIPTION
**Pull request by kortschak**
Fix breakage cause by mat64/blas64/blas restructuring.

### CODE REVIEW

**Comment by jonlawlor** [comment]
Needs a `go fmt` otherwise LGTM

**Comment by kortschak** [comment]
This failure is identical to the failure I get with optimize, gonum/matrix and gonum/blas each at master. I don't see a previous failure on travis, so I do understand how this can be.

**Comment by kortschak** [comment]
Curious - goimports failed me.

**Comment by jonlawlor** [comment]
go fmt and goimports uses a different ordering for the packages sometimes.  Also, the travis build looks fine, I think it just got into a race condition in the coverage publishing.

**Comment by kortschak** [comment]
goimports import order will be kept by gofmt, but gofmt ordering may be changed by goimports.

**Pull request merged**
